### ISSUE TITLE
When i link to other page i got error

### ISSUE THREAD

**Issue by Wchindanai** [Knape/react-typeout#1]
When i redirect to other page i got error from TypeOut component 
"setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the TypeOut component."

**Comment by Knape** [comment]
Thank you for reporting the bug, a complete oversight on my part. I have updated the library so it unmounts correctly.

Will close this issue but feel free to open another if you still encounter any problems.
