### ISSUE TITLE
PropTypes warning

### ISSUE THREAD

**Issue by collingo** [Knape/react-typeout#2]
Hi Knape, firstly, thanks for this great component!

Just one minor issue, I'm seeing PropType warnings in my logs when using this with React `15.4.2`. I see there was a commit on master back in June to use the `prop-types` package which I believe should address the warning. Any chance this will be released soon?

**Comment by Knape** [comment]
Thank you for noticing. I have pushed a new version containing the inclusion of prop-types. 
I will mark this as solved but if you find anything else, feel free to open another issue.
